title: Northern Information
author: Tyler Etters
description: Midwestern musician holed-up in the mountains by Los Angeles.
twitter_site: "@tyleretters"
twitter_creator: "@tyleretters"
twitter_image_src: /applied-sciences-and-phantasms-working-division.png
og_image: /applied-sciences-and-phantasms-working-division.png
github: https://github.com/tyleretters/nor.the-rn.info/blob/main
baseurl: /
url: https://nor.the-rn.info
permalink: /:year/:month/:day/:title
sort_by: year, month
encoding: utf-8
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
include: ["_pages"]
excerpt_separator: <!--x-->
sass:
  quiet_deps: true
